apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linkding-ingress
spec:
  rules:
  - host: linkding.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: linkding-svc
            port:
              number: 80
